name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: list and read file
          run: | 
            echo "My first Github Action job"
            ls -a
            cat README.md
        
        - name: Generate ASCII
          run: cowsay -f dragon "Run for cover, I am a dragon!" >> dragon.txt



